import os
tools = ['ddssvc', 'qtt_qtconfig', 'dorade', 'radd_archiver', 'utilities']
env = Environment(tools = ['default'] + tools)

# libraries:
libs = Split("""
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")
env.Append(LIBS = libs)

sources = Split('''
EldoraArchiver.cpp
DoradeHeader.cpp
DoradeHskp.cpp
''')

# build eldoraprod
eldoraarchiver = env.Program('EldoraArchiver', sources)
inst = env.InstallProgram(eldoraarchiver)

env.Default(eldoraarchiver)
env.Alias('install', inst)

dumper = env.Program('dumpEldoraFieldFormat', 'dumpEldoraFieldFormat.cpp')
instDumper = env.InstallProgram(dumper)

env.Default(dumper)
env.Alias('install', instDumper)



