import SCons.Tool
env = Environment()
# If we cannot load the VxWorks cross-compiler tool, then skip building
# this directory.
if (not Tool('gcc68k').exists(env)):
    print
    print "Cannot load tool 'gcc68k', so vx-eldora build will be skipped"
    print
    Return()

SConscript('xmlrpc++0.7/SConscript')
