env = Environment(tools = ["default"])

sources = Split("""
""")

headers = Split("""
HskpCommandDefs.h
HskpStatus.h
HskpStatusDefs.h
""")

rpcdefs = Split("""
HskpControl.x
""")

for x in rpcdefs:
    headers += env.RPCGenHeader(x)

env.Install("../include", headers)

env.RPCGenClient(rpcdefs)
