import os

env = Environment(ENV = os.environ)
env['RR314_ROOT'] = os.environ.get('RR314_ROOT',None)
env.AppendUnique(CPPPATH=['$RR314_ROOT',])
env.AppendUnique(CCFLAGS=['-D LINUX',])

# libraries:
libs = Split("""
rr314
channeladapter
pthread
""")

# library paths:
libpaths=Split("""
$RR314_ROOT/linux_x86-32
#/redrapids
""")

# Build tom
sources = Split("""
channeladapter_DDCx4.c
""")

tom = env.Program('tom', sources,
   LIBS=libs, LIBPATH=libpaths )

