import os

tools = ['default', 'ddssvc', 'qt4']

env = Environment(tools = tools, ENV=os.environ)

env['QWTDIR'] = os.environ.get('QWTDIR', None)

# set the include paths
env.AppendUnique(CPPPATH = ['#/qttoolbox','#/qttoolbox/ScopePlot'])
env.AppendUnique(CPPPATH = ['$QWTDIR/include',])

env.AppendUnique(CPPPATH=['#/sdrscope',])

env.Append(LIBPATH = [
	'#/qttoolbox/ScopePlot',
	'#/sdrscope',
	'$QWTDIR/lib',
	'/usr/local/lib'])

# libraries:
libs = Split("""
sdrscope
qwt
fftw3
scopeplot
""")

env.AppendUnique(LIBS = libs)

# enable the qt4 modules
env.EnableQt4Modules(['QtCore','QtGui','QtOpenGL', 'QtXml',])

sources = ['main.cpp',]

eldorascope = env.Program(
	'eldorascope', sources
	)
	
Default(eldorascope)
