import os

tools = ['default', 'ddssvc', 'qt4']

env = Environment(tools = tools)

env['QWTDIR'] = os.environ.get('QWTDIR', None)

# set the include paths

# QtToolbox items
env.AppendUnique(CPPPATH = [
'#/qttoolbox',
'#/qttoolbox/ScopePlot',
'#/qttoolbox/Knob',
'#/qttoolbox/QtConfig'])

# QWT
env.AppendUnique(CPPPATH = ['$QWTDIR/include',])

# sdr scope
env.AppendUnique(CPPPATH=['#/sdrscope',])

env.Append(LIBPATH = [
	'#/qttoolbox/ScopePlot',
	'#/qttoolbox/Knob',
	'#/qttoolbox/QtConfig',
	'#/sdrscope',
	'$QWTDIR/lib',
	'/usr/local/lib'])

# libraries:
libs = Split("""
sdrscope
qwt
fftw3
scopeplot
knob
qtconfig
boost_program_options
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")

env.AppendUnique(LIBS = libs)

# enable the qt4 modules
env.EnableQt4Modules(['QtCore','QtGui','QtOpenGL', 'QtXml',])

sources = ['main.cpp','EldoraScopeReader.cpp']

eldorascope = env.Program(
	'eldorascope', sources
	)
	
Default(eldorascope)

# This will create ui_EldoraScope.h
env.Uic4(['EldoraScope.ui',])

sources = ['newmain.cpp','EldoraScope.cpp', 'EldoraScopeReader.cpp', 'PlotInfo.cpp']

neweldorascope = env.Program(
	'neweldorascope', sources
	)
	
Default(neweldorascope)

