/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "mini.h"

bool_t
xdr_MinirimsCommand(register XDR *xdrs, MinirimsCommand *objp)
{

	register long *buf;

	if (!xdr_u_long(xdrs, &objp->cmd))
		return (FALSE);
	return (TRUE);
}

bool_t
xdr_MinirimsStatus(register XDR *xdrs, MinirimsStatus *objp)
{

	register long *buf;

	if (!xdr_u_long(xdrs, &objp->status))
		return (FALSE);
	return (TRUE);
}
