import os
tools = Split("""
ddssvc
rr314
boost_program_options
dorade
bittware
utilities
deploy
""")
env = Environment(tools = ['default'] + tools)

# libraries:
libs = Split("""
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")

env.Append(LIBS = libs)

# build dual board application
eldoradrx = env.Program('eldoradrx', ['RR314dual.cpp', 'DrxRPC.cpp'])

Default(eldoradrx)

env.DeployProgram(eldoradrx)


