env = Environment(tools = ['default'])

sources = Split("""
ddsmenu.cpp
ddsprogrammer_cpp.cpp
dds.cpp
dectohex.cpp
delay.cpp
etherio24.cpp
hextodec.cpp
mygetline.cpp
rfinit.cpp
rfputval.cpp
samenu.cpp
sa.cpp
trigmuxmenu.cpp
trigmux.cpp
""")

ecbmain = env.Program('ecbmain', sources)
i1 = env.InstallProgram(ecbmain)
env.Default(ecbmain)
env.Alias('install',i1)

# Program to set the IP address for an EtherIO24 card
ether_setup = env.Program('etherio_setup/ether_setup', ['etherio_setup/ether_setup.c'])
i2 = env.InstallProgram(ether_setup)
Default(ether_setup)
env.Alias('install',i2)
