env = Environment(tools = ['default', 'boost_program_options'])

libsources = Split("""
ddsmenu.cpp
dds.cpp
dectohex.cpp
delay.cpp
etherio24.cpp
hextodec.cpp
mygetline.cpp
rfinit.cpp
rfputval.cpp
samenu.cpp
sa.cpp
trigmuxmenu.cpp
trigmux.cpp
""")

# a library of all of the ecb support routines
ecblib = env.Library('ecb', libsources)
env.Append(LIBS=[ecblib])

# menu drive app for programming dds, attenuators, or trigger mux
ecbmain = env.Program('ecbmain', 'ddsprogrammer_cpp.cpp')
Default(ecbmain)
i1 = env.InstallProgram(ecbmain)
env.Alias('install',i1)

# command line programming of the dds
progdds = env.Program('progdds', 'progdds.cpp')
Default(progdds)
progddsi = env.InstallProgram(progdds)
env.Alias('install', progddsi)

# command line programming of the sa
progsa = env.Program('progsa', 'progsa.cpp')
Default(progsa)
progsai = env.InstallProgram(progsa)
env.Alias('install', progsai)

# command line programming of the trigger mux
progmux = env.Program('progmux', 'progmux.cpp')
Default(progmux)
progmuxi = env.InstallProgram(progmux)
env.Alias('install', progmuxi)

# Program to set the IP address for an EtherIO24 card
ether_setup = env.Program('etherio_setup/ether_setup', ['etherio_setup/ether_setup.c'])
i2 = env.InstallProgram(ether_setup)
Default(ether_setup)
env.Alias('install',i2)
