# -*- python -*-
 
import os

tools = ['default', 'qt4', 'fftw']
env = Environment(tools = tools, ENV=os.environ)

env['QWTDIR'] = os.environ.get('QWTDIR', None)

# set the include paths
env.AppendUnique(CPPPATH = ['#/qttoolbox',])
env.AppendUnique(CPPPATH = ['#/qttoolbox/ScopePlot',])
env.AppendUnique(CPPPATH = ['$QWTDIR/include',])

# add library path for the QtToolbox
env.Append(LIBPATH = ["../qttoolbox/ScopePlot",])

# and add the QtToolbox scopeplot library
env.Append(LIBS = ['scopeplot',])

# enable the qt4 modules
env.EnableQt4Modules(['QtCore','QtGui','QtOpenGL', 'QtXml',])

# This will create ui_SdrScope.h
env.Uic4(['SdrScope.ui',])

sources = Split("""
SdrScope.cpp
""")

sdrscopelib = env.Library('sdrscope', sources)

Default(sdrscopelib)
