import os

# Only build eldoradrx if the DSP21KSF environment variable is set.  This
# allows for still building everything else on systems without the bittware 
# development system installed.
if (not os.environ.has_key('DSP21KSF')):
    print
    print "No eldoradrx build: environment variable 'DSP21KSF' is not set"
    print    
    Return()
    
tools = Split("""
ddssvc
rr314
boost_program_options
dorade
bittware
utilities
qtt_qtconfig
""")
env = Environment(tools = ['default'] + tools)

sources = Split("""
eldoradrx.cpp
DrxRPC.cpp
HskpMerger.cpp
""")

# libraries:
libs = Split("""
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")

env.Append(LIBS = libs)

eldoradrx = env.Program('eldoradrx', sources)
inst = env.InstallProgram(eldoradrx)
env.Default(eldoradrx)
env.Alias('install',inst)
