import os
tools = ['ddssvc', 'qtt_qtconfig', 'utilities', 'boost_program_options']
env = Environment(tools = ['default'] + tools)

# libraries:
libs = Split("""
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")
env.Append(LIBS = libs)

sources = Split('''
main.cpp
EldoraProductsMain.cpp
EldoraProducts.cpp
ProductsRayReader.cpp
RayCollator.cpp
ProductsRPC.cpp
''')

# build eldoraprod
eldoraprod = env.Program('eldoraprod', sources)
inst = env.InstallProgram(eldoraprod)

env.Default([eldoraprod,inst])


