import os

env = Environment(ENV = os.environ)
env['RR314_ROOT'] = os.environ.get('RR314_ROOT',None)
env.AppendUnique(CPPPATH=['$RR314_ROOT',])
env.AppendUnique(CCFLAGS=['-D LINUX',])

# libraries:
libs = Split("""
ca
channeladapter
pthread
""")

# library paths:
libpaths=Split("""
$RR314_ROOT/linux_x86-32
#/tmp
""")

# The sources
sources = Split("""
FilterSpec.cpp
RR314.cpp
RR314isr.cpp
""")

librr314 = env.Library('rr314', sources,
   LIBS=libs, LIBPATH=libpaths )

# build test
testrr314 = env.Program('testrr314', 'test.cpp', LIBS=[librr314,libs], LIBPATH=libpaths)
