import os

env = Environment(ENV = os.environ)
env['RR314_ROOT'] = os.environ.get('RR314_ROOT',None)
env.AppendUnique(CPPPATH=['$RR314_ROOT',])
env.AppendUnique(CPPPATH=['/usr/local/include/boost-1_34_1',])
env.AppendUnique(CCFLAGS=['-D LINUX',])

# The library sources
sources = Split("""
$RR314_ROOT/ca_functions.c
$RR314_ROOT/ca_membuffer.c
FilterSpec.cpp
RR314.cpp
RR314isr.cpp
RR314sim.cpp
""")

librr314 = env.Library('rr314', sources )

# libraries:
libs = Split("""
rr314
channeladapter
rr314
channeladapter
pthread
boost_program_options-gcc41-1_34_1.a
""")

# library paths:
libpaths=Split("""
$RR314_ROOT/linux_x86-32
/usr/local/lib/
.
""")

# build test
testrr314 = env.Program('testrr314', 'test.cpp', LIBS=libs, LIBPATH=libpaths)
