import os

env = Environment(ENV = os.environ)
env['TAO_ROOT'] = os.environ.get('TAO_ROOT',None)
env['ACE_ROOT'] = os.environ.get('ACE_ROOT',None)
env['DDS_ROOT'] = os.environ.get('DDS_ROOT',None)
env.AppendUnique(CPPPATH=['$TAO_ROOT',])
env.AppendUnique(CPPPATH=['$ACE_ROOT',])
env.AppendUnique(CPPPATH=['$DDS_ROOT',])
env.AppendUnique(CPPPATH=['#./ddslib',])
env.AppendUnique(CCFLAGS=['-g',])

# sources
sources = Split("""
DDSPublisher.cpp
DDSWriter.cpp
DDSSubscriber.cpp
DDSReader.cpp
ArgvParams.cpp
""")

subscriber = env.Library('ddssvc', sources)
