import os
tools = ['ddssvc', 'qtt_qtconfig', 'utilities', 'deploy']
env = Environment(tools = ['default'] + tools)

# libraries:
libs = Split("""
boost_program_options
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")
env.Append(LIBS = libs)

sources = Split('''
EldoraProductsMain.cpp
EldoraProducts.cpp
ProductsPulseReader.cpp
PulseCollator.cpp
''')

# build eldoraprod
eldoraprod = env.Program('eldoraprod', sources)

Default(eldoraprod)

env.DeployProgram(eldoraprod)

