# -*- python -*-
env = Environment(tools = ["default", "vxworks"])

sources = Split("""
cio.c
dport.c
mbox.c
""")

env.Append(CPPDEFINES = ['TP41LIB'])
l = env.Library("tp41", sources)
li = env.InstallLibrary(l)
Default(li)
