# -*- python -*-

Import('env')
env = env.Copy()

sources = Split("""
cio.c
dport.c
mbox.c
""")

env.Append(CPPDEFINES = ['TP41LIB'])
env.Append(CPPPATH = ['#/vx/config/eldora.tp41'])
l = env.Library("tp41", sources)
li = env.InstallLibrary(l)
Default(li)
