import os

tools = Split("""
""")
env = Environment(tools = ['default'] + tools)
env.AppendUnique(CPPPATH='#/vx-eldora/rpc/include')
env.AppendUnique(LIBS=['m',])

makersrcs = Split('''
gen_field.c
read_header.c 
fieldradar.c 
cellspacing.c
waveform.c 
volume.c 
radar.c 
parameter.c 
engin.c
navigation.c 
insitudata.c 
set_physical.c 
big_little.c
make_new.c 
verify.c 
unpack_hd.c
re_cal.c
''')
	  
maker = env.Program('headermaker', makersrcs)
instm = env.InstallProgram(maker)
env.Default([maker,instm])

dumpsrcs = Split('''
dumpheader.c
read_header.c 
fieldradar.c 
cellspacing.c
waveform.c 
volume.c 
radar.c 
parameter.c 
navigation.c
big_little.c
unpack_hd.c
verify.c
''')

dumpheader = env.Program('dumpheader', dumpsrcs)
instd = env.InstallProgram(dumpheader)
env.Default([dumpheader,instd])


