module EldoraDDS {

enum RadarChoice {Forward, Aft};
typedef sequence<float> A_B_P;
typedef sequence<float> Product;
typedef sequence<short> TS;
  
#pragma DCPS_DATA_TYPE "EldoraDDS::TimeSeries"
#pragma DCPS_DATA_KEY  "EldoraDDS::TimeSeries radarId"

  struct TimeSeries {
    RadarChoice radarId;
    long long timestamp;
    float prfSeconds;
    float azDegrees;
    long nci;
    unsigned short chan;
    unsigned short firstgate;
    TS tsdata;
  };

#pragma DCPS_DATA_TYPE "EldoraDDS::Pulse"
#pragma DCPS_DATA_KEY  "EldoraDDS::Pulse radarId"

  struct Pulse {
    RadarChoice radarId;
    long long timestamp;
    float prfSeconds;
    float azDegrees;
    float powerDbm;
    long nci;
    unsigned short chan;
    A_B_P abp;
  };

#pragma DCPS_DATA_TYPE "EldoraDDS::Products"
#pragma DCPS_DATA_KEY  "EldoraDDS::Products radarId"

  struct Products {
    RadarChoice radarId;
    long long timestamp;
    float prfSeconds;
    float azDegrees;
    float gateSpacingKm;
    Product p1;
    Product p2;
    Product p3;
    Product p4;
    Product dbm;
    Product dbz;
    Product vel;
    Product width;
    Product snr;
    Product ncp;
  };

#pragma DCPS_DATA_TYPE "EldoraDDS::HouseKeeping"
#pragma DCPS_DATA_KEY  "EldoraDDS::HouseKeeping radarId"

  struct HouseKeeping {
    RadarChoice radarId;
    long long timestamp;
    float pitch;
    float roll;
    float yaw;
  };
};
