tools = ['ace', 'tao', 'opendds']
env = Environment(tools = ['default'] + tools)

def ddslib(env):
    env.AppendLibrary('EldoraDds')
    env.AppendUnique(CPPPATH = ['#/ddslib',])
    env.Require(tools)

Export('ddslib')

libEldoraDds = env.DdsLibrary('EldoraDds.idl', env)

