tools = ['default', 'ddssvc', 'ddsqt', 'qtt_knob', 'qtt_qtconfig', 'qtt_scopeplot', 'fftw', 'utilities', ]
env = Environment(tools = tools)

# libraries:
libs = Split("""
boost_program_options
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")

env.AppendUnique(LIBS = libs)

# This will create ui_EldoraScope.h
env.Uic4(['EldoraScope.ui',])

sources = Split("""
EldoraScopeMain.cpp
EldoraScope.cpp
PlotInfo.cpp
""")

eldorascope = env.Program('eldorascope', sources)
inst = env.InstallProgram(eldorascope)
	
Default([eldorascope,inst])

#env.DeployProgram(eldorascope)


