# -*- python -*-
# $Id$

import os, os.path, sys
import eol_scons

def VxEldora(env):
    env.AppendUnique(CCFLAGS = ["-O", "-fvolatile"])
    env.AppendUnique(LIBPATH = [os.path.join(env["INSTALL_LIBDIR"], "lib")])
    env['COMMONS'] = "/net/projects/common"
    
eol_scons.GlobalTools().extend([VxEldora, "gcc68k"])

#
#
#
#COMMONS = "/net/projects/common"
#Export('COMMONS')
#
#env.Require(["PKG_VXWORKS"])
#VXDIR = "$VXDIR"
#VXCONFIG = "$VXDIR/config/eldora.tp41"
#Export('VXDIR')
#Export('VXCONFIG')

dirs = Split("""
vx
rpc
""")
    
SConscript(dirs = dirs)

env = Environment(tools = ["default"])
options = eol_scons.GlobalOptions()
options.Update(env)
Help(options.GenerateHelpText(env))
