# -*- python -*-
# $Id$

import os, os.path, sys
sys.path.insert(0, os.path.join(os.getcwd(), 'config'))
import atd_scons

options = atd_scons.Pkg_Options()

env = atd_scons.Pkg_Environment(tools = ["default"])
env['COMMONS'] = "/net/projects/common"

env.Require(["PKG_VXWORKS"])
env['VXCONFIG'] = "$VXDIR/config/eldora.tp41"
env.Append(CPPPATH = ["$VXCONFIG"])

env.Tool("gcc68k")

env.AppendUnique(LIBPATH = ["#/lib"])
env.Append(CCFLAGS = ['-O', '-fvolatile'])
Export('env')

dirs = Split("""
vx
rpc
""")
    
SConscript(dirs = dirs)

options.Update(env)
Help(options.GenerateHelpText(env))
