tools = ['default', 'ddssvc', 'ddsqt', 'qtt_qtconfig', 'qtt_ppi', 'utilities', 'doxygen', ]
env = Environment(tools = tools)

# libraries:
libs = Split("""
boost_program_options
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")

env.AppendUnique(LIBS = libs)

# This will create ui_EldoraPPI.h
env.Uic4(['EldoraPPI.ui',])

# This will create ui_ColorBarsettings.h
env.Uic4(['ColorBarSettings.ui',])

sources = Split("""
EldoraPPIMain.cpp
EldoraPPI.cpp
ProductInfo.cpp
PpiManager.cpp
ColorBarSettings.cpp
""")

eldorappi = env.Program('eldorappi', sources)
	
inst = env.InstallProgram(eldorappi)
env.Default([eldorappi,inst])
