/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MINI_H_RPCGEN
#define	_MINI_H_RPCGEN

#include <rpc/rpc.h>

#ifdef __cplusplus
extern "C" {
#endif


struct MinirimsCommand {
	u_long cmd;
};
typedef struct MinirimsCommand MinirimsCommand;

struct MinirimsStatus {
	u_long status;
};
typedef struct MinirimsStatus MinirimsStatus;

#define	MinirimsControl ((unsigned long)(0x30000300))
#define	MinirimsCtrlVers ((unsigned long)(1))

#if defined(__STDC__) || defined(__cplusplus)
#define	sendMinirimsCommand ((unsigned long)(1))
extern  int * sendminirimscommand_1(struct MinirimsCommand *, CLIENT *);
extern  int * sendminirimscommand_1_svc(struct MinirimsCommand *, struct svc_req *);
#define	statusMinirims ((unsigned long)(2))
extern  struct MinirimsStatus * statusminirims_1(void *, CLIENT *);
extern  struct MinirimsStatus * statusminirims_1_svc(void *, struct svc_req *);
extern int minirimscontrol_1_freeresult(SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define	sendMinirimsCommand ((unsigned long)(1))
extern  int * sendminirimscommand_1();
extern  int * sendminirimscommand_1_svc();
#define	statusMinirims ((unsigned long)(2))
extern  struct MinirimsStatus * statusminirims_1();
extern  struct MinirimsStatus * statusminirims_1_svc();
extern int minirimscontrol_1_freeresult();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_MinirimsCommand(XDR *, MinirimsCommand*);
extern  bool_t xdr_MinirimsStatus(XDR *, MinirimsStatus*);

#else /* K&R C */
extern bool_t xdr_MinirimsCommand();
extern bool_t xdr_MinirimsStatus();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MINI_H_RPCGEN */
