dos2unix ACOMP.C ACOMP.UC
dos2unix ALIGN.C ALIGN.UC
dos2unix ALIGN_V.C ALIGN_V.UC
dos2unix ARCTAN.C ARCTAN.UC
dos2unix BLOCK_CR.C BLOCK_CR.UC
dos2unix C_ALIGN.C C_ALIGN.UC
dos2unix CRC_TASK.C CRC_TASK.UC
dos2unix DCMPI.C DCMPI.UC
dos2unix DIRCOS.C DIRCOS.UC
dos2unix ECINAV_A.C ECINAV_A.UC
dos2unix ECINAV_P.C ECINAV_P.UC
dos2unix ECINAV_V.C ECINAV_V.UC
dos2unix ERIS_TM.C ERIS_TM.UC
dos2unix ERTHAL.C ERTHAL.UC
dos2unix ERTHNAV.C ERTHNAV.UC
dos2unix EULER.C EULER.UC
dos2unix FLTSEQ_3.C FLTSEQ_3.UC
dos2unix GCOMP.C GCOMP.UC
dos2unix GLOBAL.C GLOBAL.UC
dos2unix GRAVITY.C GRAVITY.UC
dos2unix I_ALIGN.C I_ALIGN.UC
dos2unix INIT_ECI.C INIT_ECI.UC
dos2unix INIT_HAR.C INIT_HAR.UC
dos2unix INIT_NAV.C INIT_NAV.UC
dos2unix INIT_SOF.C INIT_SOF.UC
dos2unix MODECHG.C MODECHG.UC
dos2unix NAVROT.C NAVROT.UC
dos2unix NAVTASK.C NAVTASK.UC
dos2unix NAVVARS.C NAVVARS.UC
dos2unix NEALT.C NEALT.UC
dos2unix ORTHO.C ORTHO.UC
dos2unix RMRDCALC.C RMRDCALC.UC
dos2unix S_ALIGN.C S_ALIGN.UC
dos2unix TECI_INI.C TECI_INI.UC
dos2unix TSTRIMS.C TSTRIMS.UC
dos2unix UPDCON.C UPDCON.UC
dos2unix ALIGN_V.H ALIGN_V.UH
dos2unix CMDS.H CMDS.UH
dos2unix DIAG.H DIAG.UH
dos2unix ECINAV_V.H ECINAV_V.UH
dos2unix ERIS_TM_.H ERIS_TM_.UH
dos2unix FLTSEQDA.H FLTSEQDA.UH
dos2unix MATH.H MATH.UH
dos2unix NAVDATA.H NAVDATA.UH
dos2unix NAVVARS.H NAVVARS.UH
dos2unix RIMS.H RIMS.UH
dos2unix VRTXVISI.H VRTXVISI.UH
del ACOMP.C
del ALIGN.C
del ALIGN_V.C
del ARCTAN.C
del BLOCK_CR.C
del C_ALIGN.C
del CRC_TASK.C
del DCMPI.C
del DIRCOS.C
del ECINAV_A.C
del ECINAV_P.C
del ECINAV_V.C
del ERIS_TM.C
del ERTHAL.C
del ERTHNAV.C
del EULER.C
del FLTSEQ_3.C
del GCOMP.C
del GLOBAL.C
del GRAVITY.C
del I_ALIGN.C
del INIT_ECI.C
del INIT_HAR.C
del INIT_NAV.C
del INIT_SOF.C
del MODECHG.C
del NAVROT.C
del NAVTASK.C
del NAVVARS.C
del NEALT.C
del ORTHO.C
del RMRDCALC.C
del S_ALIGN.C
del TECI_INI.C
del TSTRIMS.C
del UPDCON.C
del ALIGN_V.H
del CMDS.H
del DIAG.H
del ECINAV_V.H
del ERIS_TM_.H
del FLTSEQDA.H
del MATH.H
del NAVDATA.H
del NAVVARS.H
del RIMS.H
del VRTXVISI.H
rename ACOMP.UC ACOMP.C
rename ALIGN.UC ALIGN.C
rename ALIGN_V.UC ALIGN_V.C
rename ARCTAN.UC ARCTAN.C
rename BLOCK_CR.UC BLOCK_CR.C
rename C_ALIGN.UC C_ALIGN.C
rename CRC_TASK.UC CRC_TASK.C
rename DCMPI.UC DCMPI.C
rename DIRCOS.UC DIRCOS.C
rename ECINAV_A.UC ECINAV_A.C
rename ECINAV_P.UC ECINAV_P.C
rename ECINAV_V.UC ECINAV_V.C
rename ERIS_TM.UC ERIS_TM.C
rename ERTHAL.UC ERTHAL.C
rename ERTHNAV.UC ERTHNAV.C
rename EULER.UC EULER.C
rename FLTSEQ_3.UC FLTSEQ_3.C
rename GCOMP.UC GCOMP.C
rename GLOBAL.UC GLOBAL.C
rename GRAVITY.UC GRAVITY.C
rename I_ALIGN.UC I_ALIGN.C
rename INIT_ECI.UC INIT_ECI.C
rename INIT_HAR.UC INIT_HAR.C
rename INIT_NAV.UC INIT_NAV.C
rename INIT_SOF.UC INIT_SOF.C
rename MODECHG.UC MODECHG.C
rename NAVROT.UC NAVROT.C
rename NAVTASK.UC NAVTASK.C
rename NAVVARS.UC NAVVARS.C
rename NEALT.UC NEALT.C
rename ORTHO.UC ORTHO.C
rename RMRDCALC.UC RMRDCALC.C
rename S_ALIGN.UC S_ALIGN.C
rename TECI_INI.UC TECI_INI.C
rename TSTRIMS.UC TSTRIMS.C
rename UPDCON.UC UPDCON.C
rename ALIGN_V.UH ALIGN_V.H
rename CMDS.UH CMDS.H
rename DIAG.UH DIAG.H
rename ECINAV_V.UH ECINAV_V.H
rename ERIS_TM_.UH ERIS_TM_.H
rename FLTSEQDA.UH FLTSEQDA.H
rename MATH.UH MATH.H
rename NAVDATA.UH NAVDATA.H
rename NAVVARS.UH NAVVARS.H
rename RIMS.UH RIMS.H
rename VRTXVISI.UH VRTXVISI.H