import os
tools = ['utilities',]
env = Environment(tools = ['default'] + tools)

#### Process our .ui file with pyuic4 to produce a .py file
#### containing the pyqt class implementation for our interface.

curDir = env.Dir('.').get_path(env.Dir('#'))

# The name of the .ui file
mainUiFile = curDir + '/EldoraMain.ui'
hdrViewUiFile = curDir + '/EldoraHeaderView.ui'

# The name of the generated py file. Its name will come from the
# name assigned to the top level component in the .ui file, with
# Ui_ prepended.
mainPyFile    = curDir + '/Ui_EldoraMain.py'
hdrViewPyFile = curDir + '/Ui_EldoraHeaderView.py'

# create PyFile
ui_eldoramain = env.Command('Ui_EldoraMain.py', 
                            'EldoraMain.ui', 
                            'pyuic4 -o ' + mainPyFile + ' ' + mainUiFile)

ui_eldorahdrview = env.Command('Ui_EldoraHeaderView.py',
                               'EldoraHeaderView.ui', 
                               'pyuic4 -o ' + hdrViewPyFile + ' ' + hdrViewUiFile)

Default(ui_eldoramain)
Default(ui_eldorahdrview)


main = 'eldoragui.py'

libs = Split(""" EldoraMain.py EldoraHeaderGUI.py EldoraHeader.py 
EldoraHeaderView.py EldoraRPC.py EldoraUtil.py EmitterProc.py 
ProgressStrip.py QtConfig.py RPCtestServer.py StatusGauge.py 
HpaWidget.py Hpa.py
Ui_EldoraHeaderView.py Ui_EldoraMain.py""")

instl = env.InstallPythonLibrary(libs)
instp = env.InstallProgram(main)
insth = env.InstallConfig('testheader.hd')
#env.Default([libs,instl,main,instp,insth,'testheader.hd'])
#env.Default([libs,['testheader.hd'])
env.Alias(target='install', source = instl)
env.Alias(target='install', source = instp)
env.Alias(target='install', source = insth)
