import os
tools = ['utilities',]
env = Environment(tools = ['default'] + tools)

#### Process our .ui file with pyuic4 to produce a .py file
#### containing the pyqt class implementation for our interface.

curDir = env.Dir('.').get_path(env.Dir('#'))

# The name of the .ui file
mainUiFile = curDir + '/EldoraMain.ui'
hdrViewUiFile = curDir + '/EldoraHeaderView.ui'

# The name of the generated py file. Its name will come from the
# name assigned to the top level component in the .ui file, with
# Ui_ prepended.
mainPyFile    = curDir + '/Ui_EldoraMain.py'
hdrViewPyFile = curDir + '/Ui_EldoraHeaderView.py'

# create PyFile
ui_eldoramain = env.Command('Ui_EldoraMain.py', 
                            'EldoraMain.ui', 
                            'pyuic4 -o ' + mainPyFile + ' ' + mainUiFile)

ui_eldorahdrview = env.Command('Ui_EldoraHeaderView.py',
                               'EldoraHeaderView.ui', 
                               'pyuic4 -o ' + hdrViewPyFile + ' ' + hdrViewUiFile)

Default(ui_eldoramain)
Default(ui_eldorahdrview)
