tools = ['default', 'ddssvc', 'utilities']
env = Environment(tools = tools)

# libraries:
libs = Split("""
boost_program_options
ReliableMulticast 
SimpleUnreliableDgram 
SimpleTcp
OpenDDS_Dcps
TAO_PortableServer
TAO_AnyTypeCode
dl
rt
""")
env.AppendUnique(LIBS = libs)

# Build the producer
producer = env.Program('producer', 'producer.cpp')

# Build the consumer
consumer = env.Program('consumer', ['consumer.cpp', 'Reader.cpp'])

Default(producer)

Default(consumer)

