# -*- python -*-
# $Id$

import os,os.path, sys
sys.path.insert(0, os.path.join(os.getcwd(),'config'))
import atd_scons
import SCons

atd_scons.SConsignFile()

options = atd_scons.Pkg_Options()

tooldir = DefaultEnvironment().Dir('#config').get_abspath()

def VxSetup(env):
    env.Tool("gcc68k", [tooldir])
    return env

env = atd_scons.Pkg_Environment(tools = ["default", "gcc68k"])
env.GlobalSetup ([VxSetup])
Export('env')

dirs = Split(
"""
hskp
""")
    
SConscript(dirs = dirs)

options.Update(env)
Help(options.GenerateHelpText(env))
